---
abstract: 'The power of the Sun in the palm of your hand'
author:
  - 'Al Newkirk <awncorp@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300010, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Command-Do
requires:
  Getopt::Long: 2.38
  Validation::Class: 5.95
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Command-Do
  homepage: http://ana.io/
  repository: http://github.com/alnewkirk/Command-Do.git
version: 0.03
