---
abstract: 'Simple Command-Line Interfaces'
author:
  - 'Al Newkirk <anewkirk@ana.io>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Command-Do
requires:
  Smart::Options: 0.053
  Validation::Class: 7.900052
resources:
  bugtracker: https://github.com/alnewkirk/Command-Do/issues
  homepage: http://search.cpan.org/dist/Command-Do/
  repository: git://github.com/alnewkirk/Command-Do.git
version: 0.120001
